[workspace]
members = [
    "crates/df_ddc",
    "crates/df_displmgr",
    "crates/df_displmgr_info",
    "apps/displaymanager_cli"
]
resolver = "2"

[workspace.dependencies]
serde = { version = "1.0.210", features = ["derive"] }
thiserror = { version = "1.0.63" }
clap = { version = "4.6.1", features = ["derive"] }
windows = { version = "0.58.0", features = ["Win32", "Win32_Devices", "Win32_Devices_Display", "Win32_Graphics", "Win32_Graphics_Gdi", "Win32_System", "Win32_System_Registry", "Win32_Foundation", "Win32_UI", "Win32_UI_HiDpi"] }
libc = { version = "0.2.186" }
criterion = { version = "0.4.0", features = ["async_tokio"] }
env_logger = { version = "0.11" }
tempfile = { version = "3" }
async-trait = "0.1"
futures = "0.3"
tokio = { version = "1", features = ["full"] }
serde_json = "1"
anyhow = "1.0"
drm = "0.12"
wayland-client = "0.31"
wayland-protocols = { version = "0.31", features = ["client"] }
wayland-protocols-wlr = { version = "0.3", features = ["client"] }
df_ddc = { path = "crates/df_ddc" }
df_displmgr = { path = "crates/df_displmgr" }
df_displmgr_info = { path = "crates/df_displmgr_info" }
