[package]
name = "displaymanager_studio"
version = "0.1.0"
edition = "2021"

[dependencies]
# Interne Crates (jetzt via Workspace statt absoluter Pfade)
df_ddc = { workspace = true }
df_displmgr = { workspace = true }
df_displmgr_info = { workspace = true }

# GUI & Grafik
eframe = { version = "0.27", features = ["persistence", "glow"] }
egui = "0.27"
egui_extras = { version = "0.27", features = ["syntect"] }
wgpu = "0.19"
raw-window-handle = "0.6"
bytemuck = { version = "1.13", features = ["derive"] }
image = "0.24"

# Utilities & Async
tokio = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_yaml = "0.9.34"
toml = "0.8"
clap = { workspace = true }
chrono = "0.4.44"
rfd = "0.14"
zip = "0.6"
rodio = "0.17"
parking_lot = "0.12.5"
thiserror = { workspace = true }
pollster = "0.4.0"

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.52", features = [
    "Win32_System_LibraryLoader",
    "Win32_UI_Accessibility",
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_HiDpi"
] }