name: Publish to crates.io

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Publish to crates.io
        run: |
          cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }} --manifest-path crates/df_displmgr_info/Cargo.toml
          sleep 10
          cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }} --manifest-path crates/df_ddc/Cargo.toml
          sleep 10
          cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }} --manifest-path crates/df_displmgr/Cargo.toml
          sleep 10
          cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }} --manifest-path apps/displaymanager_cli/Cargo.toml